# Site settings
title: Konstantinos Lamprou
description: Konstantinos Lamprou Github Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Konstantinos Lamprou
user_description: I'm a Business Intelligence Consultant from Greece, always searching for the next challenge. 
user_title: Business Intelligence Consultant
email: lambroukwstas@gmail.com
# twitter_username: lorem_ipsum
instagram_username: kwnstantinos_lamprou
linkedin_username: https://www.linkedin.com/in/konstantinos-lamprou-943038213/
github_username:  LamprouKon
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

